import Header from "@/components/Header";
import "../styles/globals.css";

import { DM_Sans } from "next/font/google";
import MobileNav from "@/components/ui/MobileNav";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-dm_sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${dm_sans.variable} font-sans`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
